[dino]
main = "https://discord.gg/wJa6kFjRCj"
support = "https://discord.gg/5VkFAQFzmd"

[albi]
main = "https://discord.gg/V5RMn5e8RM"

[ladybug]
main = "https://discord.gg/AeZRh9yPq3"
support = "https://discord.gg/cqMJbJjxfb"

[patologia]
main = "https://discord.gg/GQmNjd7Qyf"

[bloxy]
main = "https://discord.gg/hUP8fewgcr"

[cloudflare]
main = "https://discord.gg/cloudflaredev"

[flare]
main = "https://discord.gg/fWZ4QmzR9R"

[almora]
main = "https://discord.gg/VkfeN8DvTk"

[record]
main = "https://discord.gg/KMPe4gSHxa"

[anadius]
main = "https://discord.gg/fwShgSSY6u"

[fajneladybug]
main = "https://discord.gg/uvssQ6AGf6"

[yiffarchives]
main = "https://discord.gg/jQ4XMb9"