[dino]
main = "https://discord.gg/wJa6kFjRCj"
support = "https://discord.gg/5VkFAQFzmd"

[albi]
main = "https://discord.gg/V5RMn5e8RM"

[ladybug]
main = "https://discord.gg/AeZRh9yPq3"
support = "https://discord.gg/cqMJbJjxfb"

[patologia]
main = "https://discord.gg/GQmNjd7Qyf"

[bloxy]
main = "https://discord.gg/hUP8fewgcr"
